// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alkeqluiirmzbywixgqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsa2VxbHVpaXJtemJ5d2l4Z3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTcyMDcsImV4cCI6MjA3Mjk5MzIwN30.yfqSWksFBSEeD5DotZ5m_76QGlIRMRsQNb69HFE77wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});